name: profile
description: A package for profiliong DICOM studies.
version: 0.7.0
homepage: https://github.com/OpenDICOMweb/profile.git
author: Jim Philbin <jfphilbin@gmail.com>

environment:
  sdk: ^1.24.2

dependencies:
  core:
    path: C:/acr/odw/sdk/core
    version: ^0.7.0
  convert:
    path: C:/acr/odw/sdk/convert
    version: ^0.7.0

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test:  ^0.12.0



