name: profile
description: A package for profiliong DICOM studies.
version: 0.6.0
homepage: https://github.com/OpenDICOMweb/profile.git
author: Jim Philbin <jfphilbin@gmail.com>

environment:
  sdk: '>=2.0.0 <2.2.0'

dependencies:
  core:
    path: C:/odw/sdk/core
    version: ^0.7.6
  converter:
    path: C:/odw/sdk/converter
    version: ^0.7.5
  io_extended:
      path: C:/odw/sdk/io_extended
      version: ^0.7.5

dev_dependencies:
  benchmark_harness: any
  grinder: ^0.8.0
  test: any
  test_tools:
    path: C:/odw/test_tools
    version: any



