name: profile
description: A package for profiliong DICOM studies.
version: 0.6.0
homepage: https://github.com/OpenDICOMweb/profile.git
author: Jim Philbin <jfphilbin@gmail.com>

environment:
  sdk: '>=1.24.2 <2.1.0'

dependencies:
  dataset:
    path: C:/odw/sdk/dataset
    version: ^0.6.5
  element:
    path: C:/odw/sdk/element
    version: ^0.6.5
  dcm_convert:
    path: C:/odw/sdk/convert
    version: ^0.6.5
  system:
    path: C:/odw/sdk/system
    version: ^0.6.5

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test:  ^0.12.0



